# Generated by Django 3.1.4 on 2021-03-02 22:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('articles', '0054_portfoliostats_old_portfolio_constituents'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserPortfolio',
            fields=[
                ('portfolio_name', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('date_created', models.DateField()),
                ('execute_code', models.IntegerField(default=0)),
                ('min_health', models.FloatField()),
                ('min_yield', models.FloatField()),
                ('min_quality', models.FloatField()),
                ('min_fair_value', models.FloatField()),
                ('max_industry_rank', models.FloatField()),
                ('min_risk', models.FloatField()),
                ('min_insider_rating', models.FloatField()),
                ('min_inst_rating', models.FloatField()),
                ('allocation', models.FloatField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserPortfolioStats',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('portfolio_constituents', jsonfield.fields.JSONField(null=True)),
                ('old_portfolio_constituents', jsonfield.fields.JSONField(null=True)),
                ('portfolio_wealth_graph', jsonfield.fields.JSONField(null=True)),
                ('portfolio_health', models.FloatField(null=True)),
                ('portfolio_yield', models.FloatField(null=True)),
                ('portfolio_quality', models.FloatField(null=True)),
                ('portfolio_insider_rating', models.FloatField(null=True)),
                ('portfolio_inst_rating', models.FloatField(null=True)),
                ('portfolio_industry_rank', models.FloatField(null=True)),
                ('portfolio_fair_value', models.FloatField(null=True)),
                ('portfolio_risk', models.FloatField(null=True)),
                ('portfolio_change', models.FloatField(null=True)),
                ('portfolio_allocation', models.FloatField(null=True)),
                ('portfolio_historical_return', models.FloatField(null=True)),
                ('portfolio_historical_risk', models.FloatField(null=True)),
                ('portfolio_historical_sharpe', models.FloatField(null=True)),
                ('execute_portfolio', jsonfield.fields.JSONField(null=True)),
                ('name', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='name', to='articles.userportfolio')),
            ],
        ),
        migrations.RemoveField(
            model_name='portfoliostats',
            name='name',
        ),
        migrations.DeleteModel(
            name='Portfolio',
        ),
        migrations.DeleteModel(
            name='PortfolioStats',
        ),
    ]
