# Generated by Django 3.1.4 on 2021-03-20 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0055_auto_20210302_2255'),
    ]

    operations = [
        migrations.AddField(
            model_name='userportfolio',
            name='industry',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
