# Generated by Django 3.1.4 on 2021-03-23 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0056_userportfolio_industry'),
    ]

    operations = [
        migrations.AddField(
            model_name='finalcsv',
            name='mcap',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='userportfolio',
            name='industry',
            field=models.CharField(default='', max_length=100),
        ),
    ]
