# Generated by Django 3.1.4 on 2021-04-07 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0057_auto_20210323_1744'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='finalcsv',
            name='mcap',
        ),
        migrations.AddField(
            model_name='userportfolio',
            name='custom_portfolio',
            field=models.BooleanField(default=False),
        ),
    ]
