# Generated by Django 3.1.4 on 2021-04-08 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0058_auto_20210407_2018'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userportfolio',
            name='max_industry_rank',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='userportfolio',
            name='min_fair_value',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='userportfolio',
            name='min_health',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='userportfolio',
            name='min_insider_rating',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='userportfolio',
            name='min_inst_rating',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='userportfolio',
            name='min_quality',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='userportfolio',
            name='min_risk',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='userportfolio',
            name='min_yield',
            field=models.FloatField(null=True),
        ),
    ]
