# Generated by Django 3.1.4 on 2021-04-11 13:39

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0059_auto_20210408_1208'),
    ]

    operations = [
        migrations.AddField(
            model_name='userportfoliostats',
            name='pf_stats',
            field=jsonfield.fields.JSONField(null=True),
        ),
    ]
